from setuptools import setup, find_packages

setup(
    name="invoice_agent",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "streamlit>=1.31.0",
        "streamlit-option-menu>=0.3.12",
        "python-dotenv>=1.0.1",
        "pandas>=2.2.0",
        "numpy>=1.26.3",
        "psycopg2-binary>=2.9.9",
        "PyMuPDF>=1.23.21",
        "pytesseract>=0.3.10",
        "Pillow>=10.2.0",
        "requests>=2.31.0",
        "transformers>=4.37.2",
        "torch>=2.1.2",
        "reportlab>=4.0.9",
        "openpyxl>=3.1.2",
        "python-dateutil>=2.8.2",
        "PyYAML>=6.0.1",
        "SQLAlchemy>=2.0.0",
        "bcrypt>=4.0.1",
        "cryptography>=41.0.0",
        "pdf2image>=1.16.3",
        "aiohttp>=3.8.5",
        "tqdm>=4.65.0",
        "watchdog>=3.0.0"
    ],
    python_requires=">=3.9",
    author="Sailesh",
    author_email="your.email@example.com",
    description="An AI-powered invoice processing and management system",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
) 