[server]
port = 8502
address = "localhost"

[browser]
serverAddress = "localhost"
serverPort = 8502

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif" 